openapi: 3.0.0
info:
  version: 1.0.0
  title: API Measure Detector UI
  description: Provides a bunch of useful REST Endpoints for the Measure Detector UI
servers:
  - url: http://localhost:8080/api
    description: server
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response
  /edition/{editionID}/getPage/{pageNr}:
    get:
      summary: Returns the image file to the given page of the edition specified by the id
      operationId: getPageByPageNrAndEditionID
      parameters:
        - name: editionID
          schema:
            type: integer
          in: path
          required: true
          description: the editionID
        - name: pageNr
          schema:
            type: integer
          in: path
          required: true
          description: the Page NR
      responses:
        "200":
          description: The page as a image file
          content:
            image/png:
              schema:
                type: string
                format: binary
  /edition/runMeasureDetection/{id}:
    post:
      summary: runs the measure detection against an edition. Make sure that the measure detector is connected with the application
      operationId: runFullMeasureDetectionByEditionId
      parameters:
        - name: id
          schema:
            type: integer
          in: path
          required: true
          description: the ID of the edition to be measure-detected
      tags:
        - triggerMeasureDetection
      responses:
        "200":
          description: Expected response to a valid request
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /edition/add:
    post:
      summary: Adds a new edition + a corresponding
      operationId: addEdition
      tags:
        - edition
        - add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiOrchEditionWithFileAsString'
      responses:
        "200":
          description: Expected response to a valid request
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ApiOrchChartHome'
        "404":
          description: not found
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ApiOrchError'
        "501":
          description: server misconfiguration
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ApiOrchError'
components:
  schemas:
    ApiMeasureDetectorResult:
      type: object
      properties:
        measures:
          $ref: '#/components/schemas/MeasureBoxArray'
    MeasureBoxArray:
      type: array
      items:
        $ref: '#/components/schemas/MeasureBox'
    MeasureBox:
      type: object
      properties:
        left:
          type: string
        top:
          type: string
        right:
          type: string
        bottom:
          type: string
    ApiOrchEditionWithFile:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        createdDate:
          type: string
        type:
          type: string
        description:
          type: string
        pDFFileName:
          type: string
        pdfFile:
          type: string
          format: binary
        projectId:
          type: integer
    ApiOrchEditionWithFileAsString:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        createdDate:
          type: string
        type:
          type: string
        description:
          type: string
        pDFFileName:
          type: string
        pdfFile:
          type: string
          format: string
        projectId:
          type: integer
          format: int64
